# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dots_to_list <- function(dots) {
    .Call(`_uneval_dots_to_list`, dots)
}

is_default_ <- function(x) {
    .Call(`_uneval_is_default_`, x)
}

apply_closure_ <- function(call, fun, args, env) {
    .Call(`_uneval_apply_closure_`, call, fun, args, env)
}

find_promise <- function(name, env) {
    .Call(`_uneval_find_promise`, name, env)
}

promise_expr_ <- function(promise) {
    .Call(`_uneval_promise_expr_`, promise)
}

promise_env_ <- function(promise) {
    .Call(`_uneval_promise_env_`, promise)
}

